CREATE TABLE users (
    id bigint not null generated by default as identity primary key ,
    username varchar(50) not null unique ,
    password varchar(50) not null,
    email varchar(50) not null unique,
    name varchar(50) not null,
    surname varchar(50) not null,
    birthdate date null,
    gender char(1) null ,
    address varchar(50) null,
    role_id int not null,
    created_at timestamp not null default now(),
    CONSTRAINT fk_users_roles_role_id
                   FOREIGN KEY (role_id)
                   REFERENCES roles(id)
);

