create table locations(
    id bigint not null generated by default as identity primary key ,
    family_member_id bigint not null,
    user_id bigint not null,
    latitude double precision not null,
    longitude double precision not null,
    report_date timestamp not null default CURRENT_TIMESTAMP,
    constraint fk_locations_users_user_id foreign key (user_id) REFERENCES users(id),
    constraint fk_locations_family_members_fm_id
        foreign key (family_member_id) REFERENCES family_members(id)
);